Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EpiHotel.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RicercaPrenotazioniController.cs
using EpiHotel.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EpiHotel.Controllers
{
    public class RicercaPrenotazioniController : Controller
    {
        private readonly string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
        public ActionResult PrenotazioniPerCliente(string codiceFiscale)
        {
            List<RicercaPrenotazioniModel> prenotazioniCliente = new List<RicercaPrenotazioniModel>();

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    if (connection.State == System.Data.ConnectionState.Open)
                    {
                        string query = @"
                    SELECT Prenotazioni.*
                    FROM Prenotazioni
                    INNER JOIN Clienti ON Prenotazioni.IdCliente = Clienti.Id
                    WHERE Clienti.CodiceFiscale = @CodiceFiscale
                ";

                        using (SqlCommand cmd = new SqlCommand(query, connection))
                        {
                            cmd.Parameters.AddWithValue("@CodiceFiscale", codiceFiscale);

                            using (SqlDataReader reader = cmd.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    RicercaPrenotazioniModel prenotazione = new RicercaPrenotazioniModel
                                    {
                                        Id = Convert.ToInt32(reader["Id"]),
                                        IdCliente = Convert.ToInt32(reader["IdCliente"]),
                                        IdCamera = Convert.ToInt32(reader["IdCamera"]),
                                        DataPrenotazione = Convert.ToDateTime(reader["DataPrenotazione"]),
                                        NumeroProgressivoAnno = Convert.ToInt32(reader["NumeroProgressivoAnno"]),
                                        Anno = Convert.ToInt32(reader["Anno"]),
                                        PeriodoDal = Convert.ToDateTime(reader["PeriodoDal"]),
                                        PeriodoAl = Convert.ToDateTime(reader["PeriodoAl"]),
                                        CaparraConfirmatoria = Convert.ToDecimal(reader["CaparraConfirmatoria"]),
                                        TariffaApplicata = Convert.ToDecimal(reader["TariffaApplicata"]),
                                        PernottamentoConColazione = Convert.ToBoolean(reader["PernottamentoConColazione"]),
                                        MezzaPensione = Convert.ToBoolean(reader["MezzaPensione"]),
                                        PensioneCompleta = Convert.ToBoolean(reader["PensioneCompleta"])
                                    };

                                    prenotazioniCliente.Add(prenotazione);
                                }
                            }
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Errore durante l'apertura della connessione al database";
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Errore durante la ricerca delle prenotazioni per il cliente: " + ex.Message;
            }

            return View(prenotazioniCliente);
        }


        public ActionResult NumeroPrenotazioniPensioneCompleta()
        {
            int? numeroPrenotazioniPensioneCompleta = null;

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    if (connection.State == System.Data.ConnectionState.Open)
                    {
                        string query = @"
                    SELECT COUNT(*) AS NumeroPrenotazioni
                    FROM Prenotazioni
                    WHERE PensioneCompleta = 1
                ";

                        using (SqlCommand cmd = new SqlCommand(query, connection))
                        {
                            using (SqlDataReader reader = cmd.ExecuteReader())
                            {
                                if (reader.Read())
                                {
                                    numeroPrenotazioniPensioneCompleta = Convert.ToInt32(reader["NumeroPrenotazioni"]);
                                }
                            }
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Errore durante l'apertura della connessione al database";
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Errore durante il recupero del numero di prenotazioni per pensione completa: " + ex.Message;
            }

            ViewBag.NumeroPrenotazioniPensioneCompleta = numeroPrenotazioniPensioneCompleta;
            return View();
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pannello di controllo prenotazioni</h2>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Inserisci Nuova Prenotazione</h5>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Prenotazione", "Prenotazione")'">Vai</button>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Visualizza Elenco Prenotazioni</h5>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("ElencoPrenotazioni", "Prenotazione")'">Vai</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Prenotazioni per Cliente</h5>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("PrenotazioniPerCliente", "RicercaPrenotazioni")'">Vai</button>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Numero Prenotazioni Pensione Completa</h5>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("NumeroPrenotazioniPensioneCompleta", "RicercaPrenotazioni")'">Vai</button>
                </div>
            </div>
        </div>
    </div>
</div>